engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- .git/**
- tests/**
- vendor/**
