language: php

php:
- 7.1

sudo: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnupg2 libgpgme11-dev

before_script:
  - pecl install gnupg
  - composer self-update
  - composer install -n --no-scripts

script:
  - ./vendor/bin/phpcs --standard=psr2 -n --ignore=vendor .
  - travis_wait 40 ./vendor/bin/phpunit
